#!/usr/bin/env python3
import subprocess
import sys
import yaml


def copy_scripts(node, source, dest):
    login = user + '@' + node
    destination = login + ':{}'.format(dest)
    scp = subprocess.Popen(['scp', source, destination],
                           stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE)
    scp.wait()


def launch_job(node, cmd):
    login = user + '@' + node
    ssh = subprocess.Popen(['ssh', '-f', login, 'nohup {}'.format(cmd)],
                           shell=False,
                           stdout=subprocess.PIPE,
                           stderr=subprocess.PIPE)
    return ssh


def load_config_file():
    with open(joblist) as yamlfile:
        job_dict = yaml.load(yamlfile)
    user = job_dict['user']
    try:
        globaldir = job_dict['globaldir']
    except KeyError:
        globaldir = None
    nodes = job_dict['nodes']
    for node in nodes.keys():
        copy_scripts(node, node['exe'], globaldir)
        launch_job(node)


if __name__ == '__main__':
    joblist = sys.argv[1]
